### ISSUE TITLE
where did u get the emails?

### ISSUE THREAD

**Issue by kARTechnology** [jeffryanto/SendGrid-BulkMail-php-Api-samplejeff#1]
how did you get my email?
karthikx10@gmail.com
Not only me I see **all** of my friends too...where did u get the data from???

**Comment by jeffryanto** [comment]
No need to panic . The mail list has been removed now ! I work at NPTEL IIT Madras that is how I got your mail id . We use SendGrid to send Bulk mails to candidates . I forgot remove the mail list while pushing it in .

**Comment by kARTechnology** [comment]
okay!
